[package]
name = "spin_proto"
version = "0.1.0"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
license = "GPL-2.0"

[lib]
name = "spin_proto"
path = "lib.rs"

[dependencies]
prost = "*"
prost-derive = "*"
bytes = "*"

[build-dependencies]
prost-build = "*"
