[package]
name = "spin_devices"
version = "0.1.0"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
license = "GPL-2.0"

[lib]
name = "spin_devices"
path = "lib.rs"

[dependencies]
log = "*"
fxhash = "*"
serialport = "*"

[dependencies.spin_core]
path = "../core"
